---
title: "pivot_lobsters"
author: "KDZaria"
date: "2022-11-14"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

## attach libraries
library(tidyverse)
library(readxl)
library(here)
library(skimr)
library(kableExtra)

## read in data
lobsters <- read_xlsx("data/lobsters2.xlsx", skip = 4)

# explore data
skimr::skim(lobsters)
```

## Pivot Tables


```{r pivots}
lobsters %>% 
  group_by(year) %>% 
  summarise(count_by_year = n())

# group by multiple variables
lobsters %>% 
  group_by(site, year) %>% 
  summarise(count_by_siteyear = n())

# summarise multiple variables
siteyear_summary <- lobsters %>% 
                      group_by(site, year) %>% 
                      summarise(count_by_siteyear = n(),
                                mean_size_mm = mean(size_mm, na.rm = TRUE),
                                sd_size_mm = sd(size_mm, na.rm = TRUE))

## add median
siteyear_summary <- lobsters %>% 
                      group_by(site, year) %>% 
                      summarise(count_by_siteyear = n(),
                                mean_size_mm = mean(size_mm, na.rm = TRUE),
                                sd_size_mm = sd(size_mm, na.rm = TRUE),
                                median_size_mm = median(size_mm, na.rm = TRUE))


## inspect our new variable
siteyear_summary

## make a table with our new variable
siteyear_summary %>% 
  kable()

## plot data
ggplot(siteyear_summary,
       aes(x = year,
           y = median_size_mm)) +
  geom_col() +
  facet_wrap(~site)

## save image
ggsave("figures/lobsters-col.png")
```

`There are 6366 total lobsters included in this report.`

```{r count with dyplyr}
lobsters %>% 
  count(site, year)

##^^ that is the same as:
lobsters %>% 
  group_by(site, year) %>% 
  summarise(n = n()) %>% 
  ungroup()
```

## Mutate

Make new variables! There are a lot of times where you don’t want to summarize your data, but you do want to operate beyond the original data. This is often done by adding a column. We do this with the mutate() function from dplyr.

```{r mutate and select}

lobsters %>% 
  mutate(size_m = size_mm/1000)


#If we want to add a column that has the same value repeated, we can pass it just one value, either a number or a character string (in quotes).

lobsters_detailed <- lobsters %>% 
                        mutate(size_m = size_mm/1000,
                               millenia = 2000,
                               observer = "Allison Horst")

# select () allows us to choose, retain, and move data by columns.
lobsters_detailed %>% 
  select(date, site, size_m)

# view variable
lobsters_detailed
```


