---
title: "Creating graphs in R with `ggplot2`"
author: "KDZaria"
date: "2022-11-13"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(readxl)
library(here)
```

```{r plotting visitor to Channel Islands NP}
ca_np <- read_csv("data/ca_np.csv")

ci_np <- read_excel("data/ci_np.xlsx")

ggplot(data = ci_np, aes(x = year, y = visitors)) +
  geom_line()

gg_base <- ggplot(data = ci_np,
                  aes(x = year,
                      y = visitors))

gg_base +
  geom_point()

gg_base +
  geom_col()

gg_base + 
  geom_area()

gg_base +
  geom_line(
    colour = "darkseagreen",
    linetype = "dashed"
  )

gg_base +
  geom_point(
    colour = "darkseagreen",
    pch = 16,
    size = 3,
    alpha = 0.5
  )

gg_base +
  geom_point(
    aes(size = visitors,
        color = visitors),
    alpha = 0.5
  )

gg_base +
  geom_col(
    aes(fill = visitors)
  ) +
  theme_classic()


gg_base +
  geom_point(
    aes(size = visitors,
        colour = visitors),
    alpha = 0.5
  ) +
  theme_minimal() 

gg_base +
  geom_line(linetype = "dotted") +
  theme_bw() +
  labs(
    x = "Year",
    y = "Annual park visitors",
    title = "Channel Islands NP Visitation",
    subtitle = "(1963 - 2016)"
  )

# <!-- As long as the geoms are compatible, we can layer them on top of one another to further customize a graph -->

gg_base +
  geom_line(colour = "salmon4") +
  geom_point(colour = "orange",
             aes(size = year),
             alpha = 0.5)

# <!-- Multi-series ggplot graphs -->

ggplot(data = ca_np,
       aes(x = year,
           y = visitors,
           group = park_name)) +
  geom_line()


ggplot(data = ca_np,
       aes(x = year,
           y = visitors)) +
  geom_line(aes(colour = park_name))

gg_np <- ggplot(data = ca_np,
       aes(x = year,
           y = visitors,
           group = park_name))

# <!-- Faceting ggplot graphs -->
# When we facet graphs, we split them up into multiple plotting panels, where each panel contains a subset of the data. In our case, we’ll split the graph above into different panels, each containing visitation data for a single park.

gg_np +
  geom_line(show.legend = FALSE) +
  theme_light() +
  labs(x = "year", y = "annual visitors") +
  facet_wrap(~ park_name)

ggsave(here("figures", "np_graph.jpg"), dpi = 180, width = 8, height = 7)

```
